### ISSUE TITLE
Could not Connect to Server (IOS)

### ISSUE THREAD

**Issue by jboutros89** [jellyfin/jellyfin-ios#65]
Hello,

I am new to Jellyfin and i just loaded the Docker image.

My domain: jelly.mydomain.com works normally in HTTPS in the browser.

However, when i downloaded the IOS app, i try to insert the same URL but i am faced with a "Could not connect to server" error.

By the way, I configured JellyFin to allow secure connections using the Reverse Proxy (from the admin panel)

I will post below my Docker Compose configuration for JellyFin

```
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /home/jb/jf/config:/config
      - /home/jb/rdr/tv:/data/tvshows
      - /home/jb/rdr/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
    labels:
            - "traefik.enable=true"
            - "traefik.http.services.jf.loadbalancer.server.port=8096"
            - "traefik.http.routers.jf-secure.rule=Host(`jelly.mydomain.com`)"
            - "traefik.http.routers.jf-secure.entrypoints=websecure"
            - "traefik.http.routers.jf-secure.tls.certresolver=myresolver"
            - "traefik.http.routers.jf-secure.tls=true"

    restart: unless-stopped
```

Thank you for your assistance
